### ISSUE TITLE
1.20 Crash

### ISSUE THREAD

**Issue by IamKsandr707** [fxmorin/carpet-fixes#137]
`[19:41:05] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[19:41:06] [main/INFO]: Loading 107 mods:
	- antixray 1.3.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- armor-stand-editor 2.1.1+1.20-rc1
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- player-data-api 0.2.2+1.19.3
	   |-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	   |    \-- packet_tweaker 0.3.1+23w06a
	   \-- sgui 1.2.2+1.20
	- audioplayer 1.20-1.5.2
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   \-- fabric-command-api-v2 2.2.11+b3afc78b27
	- carpet 1.4.112+v230608
	- carpet-fixes 1.20-1.15.1
	- carpet-tis-addition 1.47.0
	   \-- conditional-mixin 0.3.2
	- chunky 1.3.90
	- dynmap 3.6-beta-1
	- easyauth 3.0.0-16
	   |-- at_favre_lib_bcrypt 0.9.0
	   |-- at_favre_lib_bytes 1.5.0
	   |-- com_mysql_mysql-connector-j 8.0.33
	   |-- de_mkammerer_argon2-jvm 2.11
	   |-- de_mkammerer_argon2-jvm-nolibs 2.11
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- net_java_dev_jna_jna 5.12.1
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_mongodb_bson 4.7.2
	   |-- org_mongodb_mongodb-driver-core 4.7.2
	   |-- org_mongodb_mongodb-driver-sync 4.7.2
	   |-- placeholder-api 2.1.1+1.20
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	        \-- packet_tweaker 0.3.1+23w06a
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.21
	- fabrictailor 2.1.2
	   |-- config2brigadier 1.2.3
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- fsit v1.2.0
	   \-- fsit-client v1.2.0
	- gottagofast 1.0.2
	- java 19
	- keepheadnames 1.5.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- ledger 1.2.8
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	        \-- packet_tweaker 0.3.1+23w06a
	- lithium 0.11.2
	- minecraft 1.20
	- sds 1.0.1
	   \-- com_googlecode_json-simple_json-simple 1.1.1
	- servercore 1.3.6+1.20
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.1+1.20
	- spark 1.10.41
	- starlight 1.1.2+fabric.dbc156f
	- styledchat 2.2.0+1.20
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.1+1.20
	   |-- player-data-api 0.2.2+1.19.3
	   \-- predicate-api 0.1.2+1.20
	- styledplayerlist 3.1.0+1.20
	   |-- placeholder-api 2.1.1+1.20
	   |-- player-data-api 0.2.2+1.19.3
	   \-- predicate-api 0.1.2+1.20
	- trimmable_tools 1.0.4
	- vcinteraction 1.20-1.0.3
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   \-- polymer-registry-sync-manipulator 0.5.0-rc.2+1.20-rc1
	- vmp 0.2.0+beta.7.93
	- voicechat 1.20-2.4.8
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
[19:41:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[19:41:06] [main/INFO]: Compatibility level set to JAVA_16
[19:41:06] [main/INFO]: Compatibility level set to JAVA_17
[19:41:07] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 2 override(s) found
[19:41:07] [main/INFO]: Successfully started async appender with [ServerGuiConsole, SysOut, File]
[19:41:09] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[19:41:09] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton, vmp]) disables it and children
[19:41:10] [main/WARN]: Error loading class: com/ishland/c2me/notickvd/common/NoTickChunkSendingInterceptor (java.lang.ClassNotFoundException: com/ishland/c2me/notickvd/common/NoTickChunkSendingInterceptor)
[19:41:18] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[19:41:19] [main/ERROR]: Mixin apply for mod carpet-fixes failed carpet-fixes.mixins.json:blockUpdates.HopperBlock_missingUpdateMixin from mod carpet-fixes -> net.minecraft.class_2377: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyArg annotation on hopperUpdate could not find any targets matching 'Lnet/minecraft/class_2377;updateEnabled(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)V' in net.minecraft.class_2377. Using refmap carpet-fixes-refmap.json [PREINJECT Applicator Phase -> carpet-fixes.mixins.json:blockUpdates.HopperBlock_missingUpdateMixin from mod carpet-fixes -> Prepare Injections ->  -> modify$zmd000$carpet-fixes$hopperUpdate(I)I -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyArg annotation on hopperUpdate could not find any targets matching 'Lnet/minecraft/class_2377;updateEnabled(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)V' in net.minecraft.class_2377. Using refmap carpet-fixes-refmap.json [PREINJECT Applicator Phase -> carpet-fixes.mixins.json:blockUpdates.HopperBlock_missingUpdateMixin from mod carpet-fixes -> Prepare Injections ->  -> modify$zmd000$carpet-fixes$hopperUpdate(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyArgInjectionInfo.<init>(ModifyArgInjectionInfo.java:45) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.2]
[19:41:19] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2377 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.2]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet-fixes.mixins.json:blockUpdates.HopperBlock_missingUpdateMixin from mod carpet-fixes] from phase [DEFAULT] in config [carpet-fixes.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyArg annotation on hopperUpdate could not find any targets matching 'Lnet/minecraft/class_2377;updateEnabled(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)V' in net.minecraft.class_2377. Using refmap carpet-fixes-refmap.json [PREINJECT Applicator Phase -> carpet-fixes.mixins.json:blockUpdates.HopperBlock_missingUpdateMixin from mod carpet-fixes -> Prepare Injections ->  -> modify$zmd000$carpet-fixes$hopperUpdate(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyArgInjectionInfo.<init>(ModifyArgInjectionInfo.java:45) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 12 more
`

Minecraft 1.20
Carpet-Fixes 1.20-1.15.1
Carpet Version 1.20-1.4.112+v230608
Mods:
anti-xray-1.3.0-Fabric-1.20
armor-stand-editor-2.1.1+1.20-rc1
audioplayer-1.20-1.5.2
carpet-fixes-1.20-1.15.1
carpet-tis-addition-mc1.20-v1.47.0
Chunky-1.3.90
Dynmap-3.6-beta-1-fabric-1.20
easyauth-mc1.20-3.0.0-16
fabric-api-0.83.0+1.20
fabric-carpet-1.20-1.4.112+v230608
fabric-language-kotlin-1.9.4+kotlin.1.8.21
fabrictailor-2.1.2
fsit-v1.2.0
gottagofast-1.0.2+1.20
KeepHeadNames-1.5.1-fabric-1.19.3
krypton-0.2.3
ledger-1.2.8
lithium-fabric-mc1.20-0.11.2
servercore-fabric-1.3.6+1.20
spark-1.10.41-fabric
starlight-1.1.2+fabric.dbc156f
styled-chat-2.2.0+1.20
styledplayerlist-3.1.0+1.20
trimmable-tools-mc1.20-v1.0.4
vcinteraction-1.20-1.0.3
vmp-fabric-mc1.20-0.2.0+beta.7.93-all
voicechat-fabric-1.20-2.4.8

**Comment by FxMorin** [comment]
This will be fixed in the next release

**Comment by FxMorin** [comment]
Fixed in 1.15.2
