### ISSUE TITLE
Crash when entering world

### ISSUE THREAD

**Issue by edwloef** [fxmorin/carpet-fixes#14]
Relevant log output:
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: categories
	at carpetfixes.helpers.RulePresets.setVanilla(RulePresets.java:79) ~[carpetfixes-1.17-0.0.9.jar:?]
	at carpetfixes.helpers.RulePresets.runChangePresetRule(RulePresets.java:12) ~[carpetfixes-1.17-0.0.9.jar:?]
	at carpetfixes.CarpetFixesServer.onServerLoaded(CarpetFixesServer.java:31) ~[carpetfixes-1.17-0.0.9.jar:?]
	at carpet.CarpetServer.lambda$onServerLoaded$0(CarpetServer.java:91) ~[fabric-carpet-1.17.1-1.4.45+v210811.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at carpet.CarpetServer.onServerLoaded(CarpetServer.java:88) ~[fabric-carpet-1.17.1-1.4.45+v210811.jar:?]
	at net.minecraft.server.MinecraftServer.handler$djh000$serverLoaded(MinecraftServer.java:5791) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:71) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

using carpetfixes-1.17-0.0.9.jar and fabric-carpet-1.17.1-1.4.45+v210811.jar

**Comment by edwloef** [comment]
Never mind, this seems to be happening across all of my carpet addons.

**Comment by FxMorin** [comment]
nice
