### ISSUE TITLE
server error pls help

### ISSUE THREAD

**Issue by He3epM** [fxmorin/carpet-fixes#175]
A potential solution has been determined, this may resolve your problem:
         
Replace mod 'ServerCore' (servercore) 1.5.1+1.20.1 with any version that is compatible with:
cardboard 6
More details:
         
Mod 'ServerCore' (servercore) 1.5.1+1.20.1 is incompatible with any version of mod 'Cardboard' (cardboard), but a matching version is present: 6!
      at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.10.jar:?]
      at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.10.jar:?]
      at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.10.jar:?]
      at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.10.jar:?]
      at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
      at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:1.0.1]

**Comment by Crystal0404** [comment]
This doesn't seem to be related to Carpet Fixes. Please remove `servercore` or `cardboard`,  as the logs indicate a conflict between the two
